fortran_compiler:
  - m2w64-toolchain_win-64                 # [win]
  - gfortran                               # [linux]
fortran_compiler_version:
  - 2.5.0                                  # [win]
  - 13.2.0                                 # [linux]
