{% set name = "quasielasticbayes" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/mantidproject/quasielasticbayes
  git_rev: v{{ version }}

build:
  skip: True  # [py<39]
  number: 0
  error_overlinking: false

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('fortran') }}              # [not win64]
    - {{ compiler('c') }}                    # [not win64]
    - {{ stdlib('c') }}                      # [not win64]
    - m2w64-toolchain_win-64 ==2.5.0         # [win64]
    - meson-python                           # [build_platform != target_platform]
  host:
    - python
    - numpy
    - pip
    - meson-python
  run:
    - python

test:
  imports:
    - quasielasticbayes
  requires:
    - pip
    - pytest
  source_files:
    - src/quasielasticbayes/test/
  commands:
    - pip check
    - pytest src/quasielasticbayes/test/

about:
  home: https://github.com/mantidproject/quasielasticbayes
  summary: A Bayesian fitting package used for fitting quasi-elastic neutron scattering data.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thomashampson
    - jhaigh0
    - robertapplin
